---
name: Yamlfix
on:
  push:
    branches: [main]
jobs:
  will-format-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create yaml file to format
        run: |
          echo 'name: "test file"' > gh_action_test.yaml 
          cp gh_action_test.yaml /tmp/initial_gh_action_test.yaml
      - name: Yamlfix
        id: yamlfix
        uses: comfucios/yamlfix-action@main
        with:
          files: gh_action_test.yaml
      - name: test if yamlfix formatted the file
        run: |-
          if diff /tmp/initial_gh_action_test.yaml gh_action_test.yaml > /dev/null; then
            echo "No changes detected in gh_action_test.yaml"
            exit 1
          else
            echo "Changes detected in gh_action_test.yaml"
          fi
